### ISSUE TITLE
Voice issue

### ISSUE THREAD

**Issue by umarbilaltech** [PHPJunior/laravel-video-chat-demo#11]
I have setup this project. The issue is my voice is coming back to me. I have check if this is an echo issue but no it's genuine issue. We both persons faced this issue.

**Comment by umarbilaltech** [comment]
Finally issue solved. I just includd `localVideo.muted = true;` in `gotStream` function.
`function gotStream(stream) {
        trace('Received local stream');
        localVideo.srcObject = stream;
        localStream = stream;
        localVideo.muted = true;
        call()
    }`

**Comment by shahroznawaz** [comment]
How did you successfully run this app? I just saw the Laravel login page and nothing else.
