### ISSUE TITLE
Setup not successfull!

### ISSUE THREAD

**Issue by delete-this-account** [PHPJunior/laravel-video-chat-demo#3]

**Comment by samimi-it** [comment]
Screen shot below:

![videochat](https://user-images.githubusercontent.com/37351787/37376623-fcd75058-271c-11e8-88da-6b984ac54a1f.png)

**Comment by samimi-it** [comment]
Screen shot below:

![videochat](https://user-images.githubusercontent.com/37351787/37376661-47de4e30-271d-11e8-8e44-5c10c21a02c0.png)
